version: "3.9"
services:
  dev: &dev
    build:
      context: .
      dockerfile: ./docker/application/Dockerfile
      network: host
      target: dev
      args:
        DOCKER_GID: 999
    image: vto-dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/app/vto_poc:cached

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
